WIP: locally graph-node point to gnosis
1Hive/honeyswap-subgraph pull request #7
Opened 2022-05-24 02:05 UTC by kamikazebr

Some config files to build graph-node locally and hardhat forks

2023-04-01 19:19 UTC, Corantin requested changes

2023-04-01 19:19 UTC, Corantin commented on hardhat/hardhat.config.js
> +        // url: "https://xdai-archive.blockscout.com",
comented code

2023-04-01 19:19 UTC, Corantin commented on package.json
> +    "@graphprotocol/graph-ts": "^0.29.1",
Could be worh it to get latest here with is "@graphprotocol/graph-ts@^0.29.3"
```suggestion
    "@graphprotocol/graph-ts": "^0.29.3",
```

2023-04-01 19:19 UTC, Corantin commented on src/mappings/core.ts
> +    return
maybe need to log warning in that case

2023-04-01 19:19 UTC, Corantin commented on src/mappings/core.ts
> +    return
same ?

2023-04-01 19:19 UTC, Corantin commented on src/mappings/core.ts
> +    return
NOt sure if we want to silent these edge case that could result in incomprehension state

2023-04-01 19:19 UTC, Corantin commented on src/mappings/core.ts
>    let mints = transaction.mints
If previously we assumed that is not null, we can either use the ! operator or log a warning that the object is null

2023-04-01 21:00 UTC, kamikazebr commented on src/mappings/core.ts
> +    return
Fixed

2023-04-01 21:00 UTC, kamikazebr commented on src/mappings/core.ts
> +    return
Fixed

2023-04-01 21:00 UTC, kamikazebr commented on src/mappings/core.ts
>    let mints = transaction.mints
Fixed

2023-04-26 01:49 UTC, kamikazebr commented
Did all changes, but looks like Github still dont allow to merge. Something wrong with the requested changes, they already outdated.

2023-04-26 01:49 UTC, merged